version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
        - build:
            filters:
              branches:
                only: master
              tags:
                only: /demo.*/

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set version
          command: |
            export SALEOR_VERSION=$(git rev-parse --short HEAD)
            if [ -n "$CIRCLE_TAG" ]; then
              export SALEOR_VERSION=$(git describe --tags)
            fi
            sed -i.bak "s#'dev'#'$SALEOR_VERSION'#" saleor/__init__.py
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --build-arg STATIC_URL=$STATIC_URL \
              -t mirumee/saleor:latest .
      - run:
          name: Run tests
          command: |
            docker run -d --name db -e POSTGRES_USER=saleor -e POSTGRES_PASSWORD=saleor postgres:9.4-alpine
            docker run --network container:db --rm -e DATABASE_URL mirumee/saleor:latest pytest
          environment:
            DATABASE_URL: postgres://saleor:saleor@localhost:5432/saleor

